name: The GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Run some JUnit tests
      - run: javac -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar OtherMarkdownParseTest.java
      - run: java -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore OtherMarkdownParseTest
